spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/crud_react_spring
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: Hikari
      auto-commit: false
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-36491716.okta.com/oauth2/default
        registration:
          okta:
            client-id: 0oa5ipb57fbrjcOBH5d7
            client-secret: bz8JNYvSHYandyajkSdcMGWw_1m2GdSDX0gkDvmr
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:db/changelog/master.xml


